name: Flake8
description: Run Flake8 
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python 3.7
    uses: actions/setup-python@v3
    with:
      python-version: "3.7"
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install flake8
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  - name: Lint with flake8
    shell: bash
    run: |
      # stop the build if there are Python syntax errors or undefined names
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistic