name: Deployment

on:
  push:
    branches: [terraform]

jobs:
  deployTerraform:
    name: Deploy AWS Infrastructure via Terraform
    # needs: flake8
    runs-on: ubuntu-latest
    outputs:
      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip}}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
        working-directory: terraform
      - name: Set output
        id: set-ip
        run: |-
          echo "instance_public_ip=$(terraform output --raw instance_public_ip)" >> $GITHUB_OUTPUT
        working-directory: terraform
  
  deployModel:
    name: Clone Model Repo and start server to serve model
    needs: deployTerraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: executing ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.deployTerraform.outputs.SERVER_PUBLIC_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            until [ -d iris ]
            do
                sleep 5
            done
            echo "File found"
            cd iris
            sudo docker compose down
            cd ..
            sudo rm -rf iris
            git clone -b docker-compose https://github.com/carloslme/tf-fastapi-docker-iris.git
            cd tf-fastapi-docker-iris
            sudo docker network create AIservice
            sudo docker compose up --build  -d --remove-orphans